In [1]:
'''
 What are the different data structures used in Tensorflow?. Give some examples 


 Tensors : 
 these are fundamental data structure in tensorflow, representing multidimensional array , that can contain multiple data types such 
 as strings, float , boolean
        Scaler : a tensor with zero dimension
        Vector : one dimensional tensor
        matrix : two dimensional tensor
        higher-order tensor : three or more dimensions ( image data )

Variable :
special kinds of tensor whose values can be updated during training , they are used to store model parameters like weights and biases

Sparse Tensor :
represent tensors with a large number of elements being zero 

Ragged Tensor :
it is containing data in variable length in different dimensions

Tensor Arrays: 
Used to handle dynamically sized arrays of tensors.


'''

'\n What are the different data structures used in Tensorflow?. Give some examples \n\n\n Tensors : \n these are fundamental data structure in tensorflow, representing multidimensional array , that can contain multiple data types such \n as strings, float , boolean\n        Scaler : a tensor with zero dimension\n        Vector : one dimensional tensor\n        matrix : two dimensional tensor\n        higher-order tensor : three or more dimensions ( image data )\n\nVariable :\nspecial kinds of tensor whose values can be updated during training , they are used to store model parameters like weights and biases\n\nSparse Tensor :\nrepresent tensors with a large number of elements being zero \n\nRagged Tensor :\nit is containing data in variable length in different dimensions\n\nTensor Arrays: \nUsed to handle dynamically sized arrays of tensors.\n\n\n'

In [2]:
'''
2) How does the TensorFlow constant differ from a TensorFlow variable? Explain with an example ? 

Tensorflow Constant : 
- it is immutable , once it is created then it cannot be changed
-constant are stored in computation graph , ideal for small and fixed size data


# Defining a constant
my_constant = tf.constant([1, 2, 3], dtype=tf.float32)

Tensorflow Variable :
- it is mutable , is designed to change it's value during the execution of the program
- Used in training of the model

# Defining a variable
my_variable = tf.Variable([1, 2, 3], dtype=tf.float32)

# Modifying the variable
my_variable.assign([4, 5, 6])  # The values can be updated


'''

"\n2) How does the TensorFlow constant differ from a TensorFlow variable? Explain with an example ? \n\nTensorflow Constant : \n- it is immutable , once it is created then it cannot be changed\n-constant are stored in computation graph , ideal for small and fixed size data\n\n\n# Defining a constant\nmy_constant = tf.constant([1, 2, 3], dtype=tf.float32)\n\nTensorflow Variable :\n- it is mutable , is designed to change it's value during the execution of the program\n- Used in training of the model\n\n# Defining a variable\nmy_variable = tf.Variable([1, 2, 3], dtype=tf.float32)\n\n# Modifying the variable\nmy_variable.assign([4, 5, 6])  # The values can be updated\n\n\n"

In [3]:
'''
Matrix Addition: Use tf.add() or the + operator.
Matrix Multiplication: Use tf.matmul() or the @ operator.
Element-wise Operations: Use specific functions like tf.add(), tf.multiply(), etc., or the corresponding operators.
'''

'\nMatrix Addition: Use tf.add() or the + operator.\nMatrix Multiplication: Use tf.matmul() or the @ operator.\nElement-wise Operations: Use specific functions like tf.add(), tf.multiply(), etc., or the corresponding operators.\n'

In [4]:
import tensorflow as tf

# Create a normal matrix A with dimensions 3x3
A = tf.random.normal(shape=(3, 3), mean=0.0, stddev=1.0)

# Display the values of matrix A
print(A.numpy())


[[ 0.42126283 -1.0929192   0.0139052 ]
 [-0.26898926  1.1504499  -1.1654966 ]
 [ 1.4671072  -1.150896    1.1415794 ]]


In [5]:

# Create a Gaussian matrix B with dimensions 4x4
B = tf.random.truncated_normal(shape=(4, 4), mean=0.0, stddev=1.0)

# Display the values of matrix B
print(B.numpy())

[[ 0.03351218 -0.5543519  -0.16061209 -0.87262386]
 [-1.3815429  -0.39078432 -1.0726889   0.08686812]
 [-0.06230154 -1.3174      0.2339513  -0.44028023]
 [ 0.707461    0.31505203 -0.9074249   0.6621182 ]]


In [6]:
# Create a matrix C with dimensions 2x2 drawn from a normal distribution
mean = 3.0
stddev = 0.5
C = tf.random.normal(shape=(2, 2), mean=mean, stddev=stddev)

# Display the values of matrix C
print(C.numpy())

[[2.9544716 2.721411 ]
 [3.5050406 3.2798185]]


In [7]:
# Step 1: Create matrices A and B
A = tf.random.normal(shape=(3, 3), mean=0.0, stddev=1.0)  # Example 3x3 matrix
B = tf.random.truncated_normal(shape=(3, 3), mean=0.0, stddev=1.0)  # Example 3x3 matrix

# Display matrices A and B
print("Matrix A:\n", A.numpy())
print("Matrix B:\n", B.numpy())

# Perform matrix addition to create matrix D
D = tf.add(A, B)  # or D = A + B
print("Matrix D (A + B):\n", D.numpy())

Matrix A:
 [[-0.23046136  1.3692015  -0.40297815]
 [ 1.6456825  -0.3357277  -0.38812593]
 [-0.8412065   0.53773445  0.82837474]]
Matrix B:
 [[-0.01738109  0.5282682  -1.2888052 ]
 [-0.17273788  1.0290114   1.1562152 ]
 [ 1.9675015  -0.46272454  1.1415381 ]]
Matrix D (A + B):
 [[-0.24784245  1.8974698  -1.6917834 ]
 [ 1.4729446   0.6932837   0.7680893 ]
 [ 1.1262951   0.07500991  1.9699129 ]]


In [8]:
# Step 2: Create matrix C with dimensions 2x2
mean = 3.0
stddev = 0.5
C = tf.random.normal(shape=(2, 2), mean=mean, stddev=stddev)

# Display matrix C
print("Matrix C:\n", C.numpy())

# Ensure D is 2x2 for multiplication; we will create a 2x2 submatrix from D
D_sub = D[:2, :2]  # Take the top-left 2x2 submatrix of D for multiplication

# Perform matrix multiplication to create matrix E
E = tf.matmul(C, D_sub)  # or E = C @ D_sub
print("Matrix E (C * D):\n", E.numpy())

Matrix C:
 [[3.283926  3.4344378]
 [2.41417   3.9526818]]
Matrix E (C * D):
 [[4.2448406 8.61219  ]
 [5.2237477 7.3211446]]
